### ISSUE TITLE
Crashes on npm run serv

### ISSUE THREAD

**Issue by DmacMcgreg** [agentframework/webstack#3]
agentframework-vue\src\lib\core\ExpressError.ts:34
    if (this.cause['context'] != null) {
                  ^
TypeError: Cannot read property 'context' of undefined
    at ServerError.toString (C:\Users\dave_\Code\VueJS\typescript\agentframework-vue\src\lib\core\ExpressError.ts:34:19)
    at Function.prepareStackTrace (C:\Users\dave_\Code\VueJS\typescript\agentframework-vue\node_modules\source-map-support\source-map-support.js:372:16)
    at Function.captureStackTrace (<anonymous>)
    at new ServerError (C:\Users\dave_\Code\VueJS\typescript\agentframework-vue\src\lib\core\ExpressError.ts:16:11)
    at GlobalMiddleware.ServerRouter (C:\Users\dave_\Code\VueJS\typescript\agentframework-vue\src\lib\router.ts:84:25)
    at GlobalMiddleware (C:\Users\dave_\Code\VueJS\typescript\agentframework-vue\src\lib\middlewares\global.middleware.ts:13:1)
    at ConstructInvocation.invoke (C:\Users\dave_\Code\VueJS\typescript\agentframework-vue\node_modules\agentframework\lib\index.js:95:148)
    at RouterAttribute.intercept (C:\Users\dave_\Code\VueJS\typescript\agentframework-vue\node_modules\agentframework\lib\index.js:113:709)
    at InceptionInvocation.invoke (C:\Users\dave_\Code\VueJS\typescript\agentframework-vue\node_modules\agentframework\lib\index.js:101:459)
    at Object.ConstructInterceptor [as construct] (C:\Users\dave_\Code\VueJS\typescript\agentframework-vue\node_modules\agentframework\lib\index.js:83:658)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! agentframework-vue@1.0.0 standalone: `ts-node src/bin/standalone.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the agentframework-vue@1.0.0 standalone script 'ts-node src/bin/standalone.ts'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the agentframework-vue package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ts-node src/bin/standalone.ts
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs agentframework-vue
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls agentframework-vue
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dave_\AppData\Roaming\npm-cache\_logs\2017-04-03T20_19_47_019Z-debug.log
[nodemon] app crashed - waiting for file changes before starting...

**Comment by e2tox** [comment]
Can you let me know which version of nodejs you currently using?

**Comment by e2tox** [comment]
Upgrade agentframework to newer version. I will close this one. Let me know if you still have this issue.
